defmodule DynamoDemo do
  use Dynamo.App

  endpoint ApplicationRouter

  config :dynamo,
    # The OTP application associated to this app
    # This is the name of the .app file generated by mix
    otp_app: :dynamo_demo,
    # The route from where public assets are served
    # You can turn off static assets by setting it to false
    public_route: "/public"

  def version do
    Keyword.get DynamoDemo.Mixfile.project, :version
  end
end
